### ISSUE TITLE
Missing R in the Github homepage: Brainfuck Enterpise Solutions

### ISSUE THREAD

**Issue by abelards** [bf-enterprise-solutions/.github#1]
Hi fantastic brainfuck people,

your github organisation page's title misses an R.
> Brainfuck Enterpise Solutions
I'm sad to say it feels like it rhymes with "despise".

Luckily your URLs and repos are "enterprise" with an R.
And this rhymes with "surprise", which feels nice.

We love you people, and you will no doubt bring much value to the enterprisey world.
Thanks and godspeed,

**Comment by aartaka** [comment]
Dear Sylvain,

Thank you for contacting us. Our engineers reviewed your ticket and fixed the title of Github organisation. We hope that there is no more confusion to it now. Thanks again for your care, we appreciate it.

Best regards,
Artyom Bologov
VP of Engineering
Brainfuck Enterpise Solutions
